import type { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI, Modality } from "@google/genai";

export const maxDuration = 60; // Extend Vercel timeout for Gemini requests

export default async function handler(req: VercelRequest, res: VercelResponse) {
    console.log(`[API /speak] Method: ${req.method} called`);

    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const { text, locale } = req.body;
        console.log(`[API /speak] Request received for locale: ${locale}`);

        if (!text) {
            console.error("[API /speak] Missing text parameter");
            return res.status(400).json({ error: 'Missing text parameter' });
        }

        const apiKey = process.env.API_KEY;
        if (!apiKey) {
            console.error("[API /speak] CRITICAL: API KEY IS MISSING IN ENVIRONMENT VARIABLES.");
            return res.status(500).json({ error: 'Missing API Key configuration on Vercel server. Please add VITE_API_KEY in the Vercel Dashboard.' });
        }

        const ai = new GoogleGenAI({ apiKey });

        console.log(`[API /speak] Calling Gemini TTS...`);
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash-preview-tts",
            contents: [{ parts: [{ text }] }],
            config: {
                responseModalities: [Modality.AUDIO],
                speechConfig: { voiceConfig: { prebuiltVoiceConfig: { voiceName: 'Kore' } } },
            },
        });

        console.log(`[API /speak] Gemini TTS response received successfully.`);
        const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;

        if (!base64Audio) {
            console.error("[API /speak] No audio data extracted from response");
            return res.status(500).json({ error: 'No audio generated by AI' });
        }

        return res.status(200).json({ audio: base64Audio });
    } catch (e: any) {
        console.error("[API /speak] Mordomo Speak Execution Error:", e);
        return res.status(500).json({
            error: 'Internal Server Error generating speech',
            message: e.message || String(e)
        });
    }
}
